version: '3'
services:
  flask:
    build:
      context: ./flask-app
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
